#############################################################################
<<<<<<< HEAD
# Makefile for building: Bin/Linux/Release/Jibril
# Generated by qmake (3.0) (Qt 5.2.1)
# Project:  Jibril.pro
# Template: app
# Command: /usr/lib/x86_64-linux-gnu/qt5/bin/qmake -spec linux-g++-64 -o Makefile Jibril.pro
=======
# Makefile for building: Jibril
# Generated by qmake (3.0) (Qt 5.5.1)
# Project:  Jibril.pro
# Template: app
# Command: C:\Qt\5.5\mingw492_32\bin\qmake.exe -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" -o Makefile Jibril.pro
>>>>>>> 8969ebdacb0db01774b5053feaf95768e380b1da
#############################################################################

MAKEFILE      = Makefile

<<<<<<< HEAD
####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -m64 -pipe -O2 -Wall -W -D_REENTRANT -fPIE $(DEFINES)
CXXFLAGS      = -m64 -pipe -O2 -Wall -W -D_REENTRANT -fPIE $(DEFINES)
INCPATH       = -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I. -I/usr/include/qt5 -I/usr/include/qt5/QtWidgets -I/usr/include/qt5/QtGui -I/usr/include/qt5/QtCore -IBin/Linux/Release/.moc
LINK          = g++
LFLAGS        = -m64 -Wl,-O1
LIBS          = $(SUBLIBS) -L/usr/X11R6/lib64 -lQt5Widgets -L/usr/lib/x86_64-linux-gnu -lQt5Gui -lQt5Core -lGL -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/lib/x86_64-linux-gnu/qt5/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = Bin/Linux/Release/.obj/

####### Files

SOURCES       = main.cpp \
		Source/Consciousness.cpp \
		Source/IntToStr.cpp \
		Source/MainWindow.cpp \
		Source/Versioning.cpp Bin/Linux/Release/.moc/moc_MainWindow.cpp
OBJECTS       = Bin/Linux/Release/.obj/main.o \
		Bin/Linux/Release/.obj/Consciousness.o \
		Bin/Linux/Release/.obj/IntToStr.o \
		Bin/Linux/Release/.obj/MainWindow.o \
		Bin/Linux/Release/.obj/Versioning.o \
		Bin/Linux/Release/.obj/moc_MainWindow.o
DIST          = /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/shell-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quick.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf \
		Jibril.pro \
		Jibril.pro
QMAKE_TARGET  = Jibril
DESTDIR       = Bin/Linux/Release/#avoid trailing-slash linebreak
TARGET        = Bin/Linux/Release/Jibril


first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	@test -d Bin/Linux/Release/ || mkdir -p Bin/Linux/Release/
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: Jibril.pro /usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64/qmake.conf /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/shell-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quick.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf \
		Jibril.pro \
		/usr/lib/x86_64-linux-gnu/libQt5Widgets.prl \
		/usr/lib/x86_64-linux-gnu/libQt5Gui.prl \
		/usr/lib/x86_64-linux-gnu/libQt5Core.prl
	$(QMAKE) -spec linux-g++-64 -o Makefile Jibril.pro
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/shell-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformsupport_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qml.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmltest.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quick.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64/qmake.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf:
=======
first: debug
install: debug-install
uninstall: debug-uninstall
QMAKE         = C:\Qt\5.5\mingw492_32\bin\qmake.exe
DEL_FILE      = del
CHK_DIR_EXISTS= if not exist
MKDIR         = mkdir
COPY          = copy /y
COPY_FILE     = copy /y
COPY_DIR      = xcopy /s /q /y /i
INSTALL_FILE  = copy /y
INSTALL_PROGRAM = copy /y
INSTALL_DIR   = xcopy /s /q /y /i
DEL_FILE      = del
SYMLINK       = $(QMAKE) -install ln -f -s
DEL_DIR       = rmdir
MOVE          = move
SUBTARGETS    =  \
		debug \
		release


debug: FORCE
	$(MAKE) -f $(MAKEFILE).Debug
debug-make_first: FORCE
	$(MAKE) -f $(MAKEFILE).Debug 
debug-all: FORCE
	$(MAKE) -f $(MAKEFILE).Debug all
debug-clean: FORCE
	$(MAKE) -f $(MAKEFILE).Debug clean
debug-distclean: FORCE
	$(MAKE) -f $(MAKEFILE).Debug distclean
debug-install: FORCE
	$(MAKE) -f $(MAKEFILE).Debug install
debug-uninstall: FORCE
	$(MAKE) -f $(MAKEFILE).Debug uninstall
release: FORCE
	$(MAKE) -f $(MAKEFILE).Release
release-make_first: FORCE
	$(MAKE) -f $(MAKEFILE).Release 
release-all: FORCE
	$(MAKE) -f $(MAKEFILE).Release all
release-clean: FORCE
	$(MAKE) -f $(MAKEFILE).Release clean
release-distclean: FORCE
	$(MAKE) -f $(MAKEFILE).Release distclean
release-install: FORCE
	$(MAKE) -f $(MAKEFILE).Release install
release-uninstall: FORCE
	$(MAKE) -f $(MAKEFILE).Release uninstall

Makefile: Jibril.pro C:/Qt/5.5/mingw492_32/mkspecs/win32-g++/qmake.conf C:/Qt/5.5/mingw492_32/mkspecs/features/spec_pre.prf \
		C:/Qt/5.5/mingw492_32/mkspecs/qdevice.pri \
		C:/Qt/5.5/mingw492_32/mkspecs/features/device_config.prf \
		C:/Qt/5.5/mingw492_32/mkspecs/qconfig.pri \
		C:/Qt/5.5/mingw492_32/mkspecs/modules/qt_lib_3dcollision.pri \
		C:/Qt/5.5/mingw492_32/mkspecs/modules/qt_lib_3dcollision_private.pri \
		C:/Qt/5.5/mingw492_32/mkspecs/modules/qt_lib_3dcore.pri \
		C:/Qt/5.5/mingw492_32/mkspecs/modules/qt_lib_3dcore_private.pri \
		C:/Qt/5.5/mingw492_32/mkspecs/modules/qt_lib_3dinput.pri \
		C:/Qt/5.5/mingw492_32/mkspecs/modules/qt_lib_3dinput_private.pri \
		C:/Qt/5.5/mingw492_32/mkspecs/modules/qt_lib_3dlogic.pri \
		C:/Qt/5.5/mingw492_32/mkspecs/modules/qt_lib_3dlogic_private.pri \
		C:/Qt/5.5/mingw492_32/mkspecs/modules/qt_lib_3dquick.pri \
		C:/Qt/5.5/mingw492_32/mkspecs/modules/qt_lib_3dquick_private.pri \
		C:/Qt/5.5/mingw492_32/mkspecs/modules/qt_lib_3dquickrenderer.pri \
		C:/Qt/5.5/mingw492_32/mkspecs/modules/qt_lib_3dquickrenderer_private.pri \
		C:/Qt/5.5/mingw492_32/mkspecs/modules/qt_lib_3drenderer.pri \
		C:/Qt/5.5/mingw492_32/mkspecs/modules/qt_lib_3drenderer_private.pri \
		C:/Qt/5.5/mingw492_32/mkspecs/modules/qt_lib_axbase.pri \
		C:/Qt/5.5/mingw492_32/mkspecs/modules/qt_lib_axbase_private.pri \
		C:/Qt/5.5/mingw492_32/mkspecs/modules/qt_lib_axcontainer.pri \
		C:/Qt/5.5/mingw492_32/mkspecs/modules/qt_lib_axcontainer_private.pri \
		C:/Qt/5.5/mingw492_32/mkspecs/modules/qt_lib_axserver.pri \
		C:/Qt/5.5/mingw492_32/mkspecs/modules/qt_lib_axserver_private.pri \
		C:/Qt/5.5/mingw492_32/mkspecs/modules/qt_lib_bluetooth.pri \
		C:/Qt/5.5/mingw492_32/mkspecs/modules/qt_lib_bluetooth_private.pri \
		C:/Qt/5.5/mingw492_32/mkspecs/modules/qt_lib_bootstrap_private.pri \
		C:/Qt/5.5/mingw492_32/mkspecs/modules/qt_lib_clucene_private.pri \
		C:/Qt/5.5/mingw492_32/mkspecs/modules/qt_lib_concurrent.pri \
		C:/Qt/5.5/mingw492_32/mkspecs/modules/qt_lib_concurrent_private.pri \
		C:/Qt/5.5/mingw492_32/mkspecs/modules/qt_lib_core.pri \
		C:/Qt/5.5/mingw492_32/mkspecs/modules/qt_lib_core_private.pri \
		C:/Qt/5.5/mingw492_32/mkspecs/modules/qt_lib_dbus.pri \
		C:/Qt/5.5/mingw492_32/mkspecs/modules/qt_lib_dbus_private.pri \
		C:/Qt/5.5/mingw492_32/mkspecs/modules/qt_lib_declarative.pri \
		C:/Qt/5.5/mingw492_32/mkspecs/modules/qt_lib_declarative_private.pri \
		C:/Qt/5.5/mingw492_32/mkspecs/modules/qt_lib_designer.pri \
		C:/Qt/5.5/mingw492_32/mkspecs/modules/qt_lib_designer_private.pri \
		C:/Qt/5.5/mingw492_32/mkspecs/modules/qt_lib_designercomponents_private.pri \
		C:/Qt/5.5/mingw492_32/mkspecs/modules/qt_lib_enginio.pri \
		C:/Qt/5.5/mingw492_32/mkspecs/modules/qt_lib_enginio_private.pri \
		C:/Qt/5.5/mingw492_32/mkspecs/modules/qt_lib_gui.pri \
		C:/Qt/5.5/mingw492_32/mkspecs/modules/qt_lib_gui_private.pri \
		C:/Qt/5.5/mingw492_32/mkspecs/modules/qt_lib_help.pri \
		C:/Qt/5.5/mingw492_32/mkspecs/modules/qt_lib_help_private.pri \
		C:/Qt/5.5/mingw492_32/mkspecs/modules/qt_lib_location.pri \
		C:/Qt/5.5/mingw492_32/mkspecs/modules/qt_lib_location_private.pri \
		C:/Qt/5.5/mingw492_32/mkspecs/modules/qt_lib_multimedia.pri \
		C:/Qt/5.5/mingw492_32/mkspecs/modules/qt_lib_multimedia_private.pri \
		C:/Qt/5.5/mingw492_32/mkspecs/modules/qt_lib_multimediawidgets.pri \
		C:/Qt/5.5/mingw492_32/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		C:/Qt/5.5/mingw492_32/mkspecs/modules/qt_lib_network.pri \
		C:/Qt/5.5/mingw492_32/mkspecs/modules/qt_lib_network_private.pri \
		C:/Qt/5.5/mingw492_32/mkspecs/modules/qt_lib_nfc.pri \
		C:/Qt/5.5/mingw492_32/mkspecs/modules/qt_lib_nfc_private.pri \
		C:/Qt/5.5/mingw492_32/mkspecs/modules/qt_lib_opengl.pri \
		C:/Qt/5.5/mingw492_32/mkspecs/modules/qt_lib_opengl_private.pri \
		C:/Qt/5.5/mingw492_32/mkspecs/modules/qt_lib_openglextensions.pri \
		C:/Qt/5.5/mingw492_32/mkspecs/modules/qt_lib_openglextensions_private.pri \
		C:/Qt/5.5/mingw492_32/mkspecs/modules/qt_lib_platformsupport_private.pri \
		C:/Qt/5.5/mingw492_32/mkspecs/modules/qt_lib_positioning.pri \
		C:/Qt/5.5/mingw492_32/mkspecs/modules/qt_lib_positioning_private.pri \
		C:/Qt/5.5/mingw492_32/mkspecs/modules/qt_lib_printsupport.pri \
		C:/Qt/5.5/mingw492_32/mkspecs/modules/qt_lib_printsupport_private.pri \
		C:/Qt/5.5/mingw492_32/mkspecs/modules/qt_lib_qml.pri \
		C:/Qt/5.5/mingw492_32/mkspecs/modules/qt_lib_qml_private.pri \
		C:/Qt/5.5/mingw492_32/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		C:/Qt/5.5/mingw492_32/mkspecs/modules/qt_lib_qmltest.pri \
		C:/Qt/5.5/mingw492_32/mkspecs/modules/qt_lib_qmltest_private.pri \
		C:/Qt/5.5/mingw492_32/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		C:/Qt/5.5/mingw492_32/mkspecs/modules/qt_lib_quick.pri \
		C:/Qt/5.5/mingw492_32/mkspecs/modules/qt_lib_quick_private.pri \
		C:/Qt/5.5/mingw492_32/mkspecs/modules/qt_lib_quickparticles_private.pri \
		C:/Qt/5.5/mingw492_32/mkspecs/modules/qt_lib_quickwidgets.pri \
		C:/Qt/5.5/mingw492_32/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		C:/Qt/5.5/mingw492_32/mkspecs/modules/qt_lib_script.pri \
		C:/Qt/5.5/mingw492_32/mkspecs/modules/qt_lib_script_private.pri \
		C:/Qt/5.5/mingw492_32/mkspecs/modules/qt_lib_scripttools.pri \
		C:/Qt/5.5/mingw492_32/mkspecs/modules/qt_lib_scripttools_private.pri \
		C:/Qt/5.5/mingw492_32/mkspecs/modules/qt_lib_sensors.pri \
		C:/Qt/5.5/mingw492_32/mkspecs/modules/qt_lib_sensors_private.pri \
		C:/Qt/5.5/mingw492_32/mkspecs/modules/qt_lib_serialport.pri \
		C:/Qt/5.5/mingw492_32/mkspecs/modules/qt_lib_serialport_private.pri \
		C:/Qt/5.5/mingw492_32/mkspecs/modules/qt_lib_sql.pri \
		C:/Qt/5.5/mingw492_32/mkspecs/modules/qt_lib_sql_private.pri \
		C:/Qt/5.5/mingw492_32/mkspecs/modules/qt_lib_svg.pri \
		C:/Qt/5.5/mingw492_32/mkspecs/modules/qt_lib_svg_private.pri \
		C:/Qt/5.5/mingw492_32/mkspecs/modules/qt_lib_testlib.pri \
		C:/Qt/5.5/mingw492_32/mkspecs/modules/qt_lib_testlib_private.pri \
		C:/Qt/5.5/mingw492_32/mkspecs/modules/qt_lib_uiplugin.pri \
		C:/Qt/5.5/mingw492_32/mkspecs/modules/qt_lib_uitools.pri \
		C:/Qt/5.5/mingw492_32/mkspecs/modules/qt_lib_uitools_private.pri \
		C:/Qt/5.5/mingw492_32/mkspecs/modules/qt_lib_webchannel.pri \
		C:/Qt/5.5/mingw492_32/mkspecs/modules/qt_lib_webchannel_private.pri \
		C:/Qt/5.5/mingw492_32/mkspecs/modules/qt_lib_webkit.pri \
		C:/Qt/5.5/mingw492_32/mkspecs/modules/qt_lib_webkit_private.pri \
		C:/Qt/5.5/mingw492_32/mkspecs/modules/qt_lib_webkitwidgets.pri \
		C:/Qt/5.5/mingw492_32/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		C:/Qt/5.5/mingw492_32/mkspecs/modules/qt_lib_websockets.pri \
		C:/Qt/5.5/mingw492_32/mkspecs/modules/qt_lib_websockets_private.pri \
		C:/Qt/5.5/mingw492_32/mkspecs/modules/qt_lib_widgets.pri \
		C:/Qt/5.5/mingw492_32/mkspecs/modules/qt_lib_widgets_private.pri \
		C:/Qt/5.5/mingw492_32/mkspecs/modules/qt_lib_winextras.pri \
		C:/Qt/5.5/mingw492_32/mkspecs/modules/qt_lib_winextras_private.pri \
		C:/Qt/5.5/mingw492_32/mkspecs/modules/qt_lib_xml.pri \
		C:/Qt/5.5/mingw492_32/mkspecs/modules/qt_lib_xml_private.pri \
		C:/Qt/5.5/mingw492_32/mkspecs/modules/qt_lib_xmlpatterns.pri \
		C:/Qt/5.5/mingw492_32/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		C:/Qt/5.5/mingw492_32/mkspecs/features/qt_functions.prf \
		C:/Qt/5.5/mingw492_32/mkspecs/features/qt_config.prf \
		C:/Qt/5.5/mingw492_32/mkspecs/features/win32/qt_config.prf \
		C:/Qt/5.5/mingw492_32/mkspecs/win32-g++/qmake.conf \
		C:/Qt/5.5/mingw492_32/mkspecs/features/spec_post.prf \
		C:/Qt/5.5/mingw492_32/mkspecs/features/exclusive_builds.prf \
		C:/Qt/5.5/mingw492_32/mkspecs/features/default_pre.prf \
		C:/Qt/5.5/mingw492_32/mkspecs/features/win32/default_pre.prf \
		C:/Qt/5.5/mingw492_32/mkspecs/features/resolve_config.prf \
		C:/Qt/5.5/mingw492_32/mkspecs/features/exclusive_builds_post.prf \
		C:/Qt/5.5/mingw492_32/mkspecs/features/default_post.prf \
		C:/Qt/5.5/mingw492_32/mkspecs/features/qml_debug.prf \
		C:/Qt/5.5/mingw492_32/mkspecs/features/win32/rtti.prf \
		C:/Qt/5.5/mingw492_32/mkspecs/features/precompile_header.prf \
		C:/Qt/5.5/mingw492_32/mkspecs/features/warn_on.prf \
		C:/Qt/5.5/mingw492_32/mkspecs/features/qt.prf \
		C:/Qt/5.5/mingw492_32/mkspecs/features/resources.prf \
		C:/Qt/5.5/mingw492_32/mkspecs/features/moc.prf \
		C:/Qt/5.5/mingw492_32/mkspecs/features/win32/opengl.prf \
		C:/Qt/5.5/mingw492_32/mkspecs/features/uic.prf \
		C:/Qt/5.5/mingw492_32/mkspecs/features/win32/windows.prf \
		C:/Qt/5.5/mingw492_32/mkspecs/features/testcase_targets.prf \
		C:/Qt/5.5/mingw492_32/mkspecs/features/exceptions.prf \
		C:/Qt/5.5/mingw492_32/mkspecs/features/yacc.prf \
		C:/Qt/5.5/mingw492_32/mkspecs/features/lex.prf \
		Jibril.pro \
		C:/Qt/5.5/mingw492_32/lib/qtmaind.prl \
		C:/Qt/5.5/mingw492_32/lib/Qt5Widgets.prl \
		C:/Qt/5.5/mingw492_32/lib/Qt5Gui.prl \
		C:/Qt/5.5/mingw492_32/lib/Qt5Core.prl
	$(QMAKE) -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" -o Makefile Jibril.pro
C:/Qt/5.5/mingw492_32/mkspecs/features/spec_pre.prf:
C:/Qt/5.5/mingw492_32/mkspecs/qdevice.pri:
C:/Qt/5.5/mingw492_32/mkspecs/features/device_config.prf:
C:/Qt/5.5/mingw492_32/mkspecs/qconfig.pri:
C:/Qt/5.5/mingw492_32/mkspecs/modules/qt_lib_3dcollision.pri:
C:/Qt/5.5/mingw492_32/mkspecs/modules/qt_lib_3dcollision_private.pri:
C:/Qt/5.5/mingw492_32/mkspecs/modules/qt_lib_3dcore.pri:
C:/Qt/5.5/mingw492_32/mkspecs/modules/qt_lib_3dcore_private.pri:
C:/Qt/5.5/mingw492_32/mkspecs/modules/qt_lib_3dinput.pri:
C:/Qt/5.5/mingw492_32/mkspecs/modules/qt_lib_3dinput_private.pri:
C:/Qt/5.5/mingw492_32/mkspecs/modules/qt_lib_3dlogic.pri:
C:/Qt/5.5/mingw492_32/mkspecs/modules/qt_lib_3dlogic_private.pri:
C:/Qt/5.5/mingw492_32/mkspecs/modules/qt_lib_3dquick.pri:
C:/Qt/5.5/mingw492_32/mkspecs/modules/qt_lib_3dquick_private.pri:
C:/Qt/5.5/mingw492_32/mkspecs/modules/qt_lib_3dquickrenderer.pri:
C:/Qt/5.5/mingw492_32/mkspecs/modules/qt_lib_3dquickrenderer_private.pri:
C:/Qt/5.5/mingw492_32/mkspecs/modules/qt_lib_3drenderer.pri:
C:/Qt/5.5/mingw492_32/mkspecs/modules/qt_lib_3drenderer_private.pri:
C:/Qt/5.5/mingw492_32/mkspecs/modules/qt_lib_axbase.pri:
C:/Qt/5.5/mingw492_32/mkspecs/modules/qt_lib_axbase_private.pri:
C:/Qt/5.5/mingw492_32/mkspecs/modules/qt_lib_axcontainer.pri:
C:/Qt/5.5/mingw492_32/mkspecs/modules/qt_lib_axcontainer_private.pri:
C:/Qt/5.5/mingw492_32/mkspecs/modules/qt_lib_axserver.pri:
C:/Qt/5.5/mingw492_32/mkspecs/modules/qt_lib_axserver_private.pri:
C:/Qt/5.5/mingw492_32/mkspecs/modules/qt_lib_bluetooth.pri:
C:/Qt/5.5/mingw492_32/mkspecs/modules/qt_lib_bluetooth_private.pri:
C:/Qt/5.5/mingw492_32/mkspecs/modules/qt_lib_bootstrap_private.pri:
C:/Qt/5.5/mingw492_32/mkspecs/modules/qt_lib_clucene_private.pri:
C:/Qt/5.5/mingw492_32/mkspecs/modules/qt_lib_concurrent.pri:
C:/Qt/5.5/mingw492_32/mkspecs/modules/qt_lib_concurrent_private.pri:
C:/Qt/5.5/mingw492_32/mkspecs/modules/qt_lib_core.pri:
C:/Qt/5.5/mingw492_32/mkspecs/modules/qt_lib_core_private.pri:
C:/Qt/5.5/mingw492_32/mkspecs/modules/qt_lib_dbus.pri:
C:/Qt/5.5/mingw492_32/mkspecs/modules/qt_lib_dbus_private.pri:
C:/Qt/5.5/mingw492_32/mkspecs/modules/qt_lib_declarative.pri:
C:/Qt/5.5/mingw492_32/mkspecs/modules/qt_lib_declarative_private.pri:
C:/Qt/5.5/mingw492_32/mkspecs/modules/qt_lib_designer.pri:
C:/Qt/5.5/mingw492_32/mkspecs/modules/qt_lib_designer_private.pri:
C:/Qt/5.5/mingw492_32/mkspecs/modules/qt_lib_designercomponents_private.pri:
C:/Qt/5.5/mingw492_32/mkspecs/modules/qt_lib_enginio.pri:
C:/Qt/5.5/mingw492_32/mkspecs/modules/qt_lib_enginio_private.pri:
C:/Qt/5.5/mingw492_32/mkspecs/modules/qt_lib_gui.pri:
C:/Qt/5.5/mingw492_32/mkspecs/modules/qt_lib_gui_private.pri:
C:/Qt/5.5/mingw492_32/mkspecs/modules/qt_lib_help.pri:
C:/Qt/5.5/mingw492_32/mkspecs/modules/qt_lib_help_private.pri:
C:/Qt/5.5/mingw492_32/mkspecs/modules/qt_lib_location.pri:
C:/Qt/5.5/mingw492_32/mkspecs/modules/qt_lib_location_private.pri:
C:/Qt/5.5/mingw492_32/mkspecs/modules/qt_lib_multimedia.pri:
C:/Qt/5.5/mingw492_32/mkspecs/modules/qt_lib_multimedia_private.pri:
C:/Qt/5.5/mingw492_32/mkspecs/modules/qt_lib_multimediawidgets.pri:
C:/Qt/5.5/mingw492_32/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
C:/Qt/5.5/mingw492_32/mkspecs/modules/qt_lib_network.pri:
C:/Qt/5.5/mingw492_32/mkspecs/modules/qt_lib_network_private.pri:
C:/Qt/5.5/mingw492_32/mkspecs/modules/qt_lib_nfc.pri:
C:/Qt/5.5/mingw492_32/mkspecs/modules/qt_lib_nfc_private.pri:
C:/Qt/5.5/mingw492_32/mkspecs/modules/qt_lib_opengl.pri:
C:/Qt/5.5/mingw492_32/mkspecs/modules/qt_lib_opengl_private.pri:
C:/Qt/5.5/mingw492_32/mkspecs/modules/qt_lib_openglextensions.pri:
C:/Qt/5.5/mingw492_32/mkspecs/modules/qt_lib_openglextensions_private.pri:
C:/Qt/5.5/mingw492_32/mkspecs/modules/qt_lib_platformsupport_private.pri:
C:/Qt/5.5/mingw492_32/mkspecs/modules/qt_lib_positioning.pri:
C:/Qt/5.5/mingw492_32/mkspecs/modules/qt_lib_positioning_private.pri:
C:/Qt/5.5/mingw492_32/mkspecs/modules/qt_lib_printsupport.pri:
C:/Qt/5.5/mingw492_32/mkspecs/modules/qt_lib_printsupport_private.pri:
C:/Qt/5.5/mingw492_32/mkspecs/modules/qt_lib_qml.pri:
C:/Qt/5.5/mingw492_32/mkspecs/modules/qt_lib_qml_private.pri:
C:/Qt/5.5/mingw492_32/mkspecs/modules/qt_lib_qmldevtools_private.pri:
C:/Qt/5.5/mingw492_32/mkspecs/modules/qt_lib_qmltest.pri:
C:/Qt/5.5/mingw492_32/mkspecs/modules/qt_lib_qmltest_private.pri:
C:/Qt/5.5/mingw492_32/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
C:/Qt/5.5/mingw492_32/mkspecs/modules/qt_lib_quick.pri:
C:/Qt/5.5/mingw492_32/mkspecs/modules/qt_lib_quick_private.pri:
C:/Qt/5.5/mingw492_32/mkspecs/modules/qt_lib_quickparticles_private.pri:
C:/Qt/5.5/mingw492_32/mkspecs/modules/qt_lib_quickwidgets.pri:
C:/Qt/5.5/mingw492_32/mkspecs/modules/qt_lib_quickwidgets_private.pri:
C:/Qt/5.5/mingw492_32/mkspecs/modules/qt_lib_script.pri:
C:/Qt/5.5/mingw492_32/mkspecs/modules/qt_lib_script_private.pri:
C:/Qt/5.5/mingw492_32/mkspecs/modules/qt_lib_scripttools.pri:
C:/Qt/5.5/mingw492_32/mkspecs/modules/qt_lib_scripttools_private.pri:
C:/Qt/5.5/mingw492_32/mkspecs/modules/qt_lib_sensors.pri:
C:/Qt/5.5/mingw492_32/mkspecs/modules/qt_lib_sensors_private.pri:
C:/Qt/5.5/mingw492_32/mkspecs/modules/qt_lib_serialport.pri:
C:/Qt/5.5/mingw492_32/mkspecs/modules/qt_lib_serialport_private.pri:
C:/Qt/5.5/mingw492_32/mkspecs/modules/qt_lib_sql.pri:
C:/Qt/5.5/mingw492_32/mkspecs/modules/qt_lib_sql_private.pri:
C:/Qt/5.5/mingw492_32/mkspecs/modules/qt_lib_svg.pri:
C:/Qt/5.5/mingw492_32/mkspecs/modules/qt_lib_svg_private.pri:
C:/Qt/5.5/mingw492_32/mkspecs/modules/qt_lib_testlib.pri:
C:/Qt/5.5/mingw492_32/mkspecs/modules/qt_lib_testlib_private.pri:
C:/Qt/5.5/mingw492_32/mkspecs/modules/qt_lib_uiplugin.pri:
C:/Qt/5.5/mingw492_32/mkspecs/modules/qt_lib_uitools.pri:
C:/Qt/5.5/mingw492_32/mkspecs/modules/qt_lib_uitools_private.pri:
C:/Qt/5.5/mingw492_32/mkspecs/modules/qt_lib_webchannel.pri:
C:/Qt/5.5/mingw492_32/mkspecs/modules/qt_lib_webchannel_private.pri:
C:/Qt/5.5/mingw492_32/mkspecs/modules/qt_lib_webkit.pri:
C:/Qt/5.5/mingw492_32/mkspecs/modules/qt_lib_webkit_private.pri:
C:/Qt/5.5/mingw492_32/mkspecs/modules/qt_lib_webkitwidgets.pri:
C:/Qt/5.5/mingw492_32/mkspecs/modules/qt_lib_webkitwidgets_private.pri:
C:/Qt/5.5/mingw492_32/mkspecs/modules/qt_lib_websockets.pri:
C:/Qt/5.5/mingw492_32/mkspecs/modules/qt_lib_websockets_private.pri:
C:/Qt/5.5/mingw492_32/mkspecs/modules/qt_lib_widgets.pri:
C:/Qt/5.5/mingw492_32/mkspecs/modules/qt_lib_widgets_private.pri:
C:/Qt/5.5/mingw492_32/mkspecs/modules/qt_lib_winextras.pri:
C:/Qt/5.5/mingw492_32/mkspecs/modules/qt_lib_winextras_private.pri:
C:/Qt/5.5/mingw492_32/mkspecs/modules/qt_lib_xml.pri:
C:/Qt/5.5/mingw492_32/mkspecs/modules/qt_lib_xml_private.pri:
C:/Qt/5.5/mingw492_32/mkspecs/modules/qt_lib_xmlpatterns.pri:
C:/Qt/5.5/mingw492_32/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
C:/Qt/5.5/mingw492_32/mkspecs/features/qt_functions.prf:
C:/Qt/5.5/mingw492_32/mkspecs/features/qt_config.prf:
C:/Qt/5.5/mingw492_32/mkspecs/features/win32/qt_config.prf:
C:/Qt/5.5/mingw492_32/mkspecs/win32-g++/qmake.conf:
C:/Qt/5.5/mingw492_32/mkspecs/features/spec_post.prf:
C:/Qt/5.5/mingw492_32/mkspecs/features/exclusive_builds.prf:
C:/Qt/5.5/mingw492_32/mkspecs/features/default_pre.prf:
C:/Qt/5.5/mingw492_32/mkspecs/features/win32/default_pre.prf:
C:/Qt/5.5/mingw492_32/mkspecs/features/resolve_config.prf:
C:/Qt/5.5/mingw492_32/mkspecs/features/exclusive_builds_post.prf:
C:/Qt/5.5/mingw492_32/mkspecs/features/default_post.prf:
C:/Qt/5.5/mingw492_32/mkspecs/features/qml_debug.prf:
C:/Qt/5.5/mingw492_32/mkspecs/features/win32/rtti.prf:
C:/Qt/5.5/mingw492_32/mkspecs/features/precompile_header.prf:
C:/Qt/5.5/mingw492_32/mkspecs/features/warn_on.prf:
C:/Qt/5.5/mingw492_32/mkspecs/features/qt.prf:
C:/Qt/5.5/mingw492_32/mkspecs/features/resources.prf:
C:/Qt/5.5/mingw492_32/mkspecs/features/moc.prf:
C:/Qt/5.5/mingw492_32/mkspecs/features/win32/opengl.prf:
C:/Qt/5.5/mingw492_32/mkspecs/features/uic.prf:
C:/Qt/5.5/mingw492_32/mkspecs/features/win32/windows.prf:
C:/Qt/5.5/mingw492_32/mkspecs/features/testcase_targets.prf:
C:/Qt/5.5/mingw492_32/mkspecs/features/exceptions.prf:
C:/Qt/5.5/mingw492_32/mkspecs/features/yacc.prf:
C:/Qt/5.5/mingw492_32/mkspecs/features/lex.prf:
>>>>>>> 8969ebdacb0db01774b5053feaf95768e380b1da
Jibril.pro:
C:/Qt/5.5/mingw492_32/lib/qtmaind.prl:
C:/Qt/5.5/mingw492_32/lib/Qt5Widgets.prl:
C:/Qt/5.5/mingw492_32/lib/Qt5Gui.prl:
C:/Qt/5.5/mingw492_32/lib/Qt5Core.prl:
qmake: FORCE
<<<<<<< HEAD
	@$(QMAKE) -spec linux-g++-64 -o Makefile Jibril.pro

qmake_all: FORCE

dist: 
	@test -d Bin/Linux/Release/.obj/Jibril1.0.0 || mkdir -p Bin/Linux/Release/.obj/Jibril1.0.0
	$(COPY_FILE) --parents $(SOURCES) $(DIST) Bin/Linux/Release/.obj/Jibril1.0.0/ && $(COPY_FILE) --parents Include/Consciousness.h Include/IntToStr.h Include/MainWindow.h Include/Versioning.h Bin/Linux/Release/.obj/Jibril1.0.0/ && $(COPY_FILE) --parents main.cpp Source/Consciousness.cpp Source/IntToStr.cpp Source/MainWindow.cpp Source/Versioning.cpp Bin/Linux/Release/.obj/Jibril1.0.0/ && (cd `dirname Bin/Linux/Release/.obj/Jibril1.0.0` && $(TAR) Jibril1.0.0.tar Jibril1.0.0 && $(COMPRESS) Jibril1.0.0.tar) && $(MOVE) `dirname Bin/Linux/Release/.obj/Jibril1.0.0`/Jibril1.0.0.tar.gz . && $(DEL_FILE) -r Bin/Linux/Release/.obj/Jibril1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) Bin/Linux/Release/$(TARGET) 
=======
	@$(QMAKE) -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" -o Makefile Jibril.pro

qmake_all: FORCE

make_first: debug-make_first release-make_first  FORCE
all: debug-all release-all  FORCE
clean: debug-clean release-clean  FORCE
distclean: debug-distclean release-distclean  FORCE
>>>>>>> 8969ebdacb0db01774b5053feaf95768e380b1da
	-$(DEL_FILE) Makefile

debug-mocclean:
	$(MAKE) -f $(MAKEFILE).Debug mocclean
release-mocclean:
	$(MAKE) -f $(MAKEFILE).Release mocclean
mocclean: debug-mocclean release-mocclean

debug-mocables:
	$(MAKE) -f $(MAKEFILE).Debug mocables
release-mocables:
	$(MAKE) -f $(MAKEFILE).Release mocables
mocables: debug-mocables release-mocables

check: first
<<<<<<< HEAD

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_header_make_all: Bin/Linux/Release/.moc/moc_MainWindow.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) Bin/Linux/Release/.moc/moc_MainWindow.cpp
Bin/Linux/Release/.moc/moc_MainWindow.cpp: Include/Versioning.h \
		Include/Consciousness.h \
		/usr/include/qt5/QtWidgets/QMainWindow \
		/usr/include/qt5/QtWidgets/qmainwindow.h \
		/usr/include/qt5/QtWidgets/qwidget.h \
		/usr/include/qt5/QtGui/qwindowdefs.h \
		/usr/include/qt5/QtCore/qglobal.h \
		/usr/include/qt5/QtCore/qconfig.h \
		/usr/include/qt5/QtCore/qfeatures.h \
		/usr/include/qt5/QtCore/qsystemdetection.h \
		/usr/include/qt5/QtCore/qprocessordetection.h \
		/usr/include/qt5/QtCore/qcompilerdetection.h \
		/usr/include/qt5/QtCore/qglobalstatic.h \
		/usr/include/qt5/QtCore/qatomic.h \
		/usr/include/qt5/QtCore/qbasicatomic.h \
		/usr/include/qt5/QtCore/qatomic_bootstrap.h \
		/usr/include/qt5/QtCore/qgenericatomic.h \
		/usr/include/qt5/QtCore/qatomic_msvc.h \
		/usr/include/qt5/QtCore/qatomic_integrity.h \
		/usr/include/qt5/QtCore/qoldbasicatomic.h \
		/usr/include/qt5/QtCore/qatomic_vxworks.h \
		/usr/include/qt5/QtCore/qatomic_power.h \
		/usr/include/qt5/QtCore/qatomic_alpha.h \
		/usr/include/qt5/QtCore/qatomic_armv7.h \
		/usr/include/qt5/QtCore/qatomic_armv6.h \
		/usr/include/qt5/QtCore/qatomic_armv5.h \
		/usr/include/qt5/QtCore/qatomic_bfin.h \
		/usr/include/qt5/QtCore/qatomic_ia64.h \
		/usr/include/qt5/QtCore/qatomic_mips.h \
		/usr/include/qt5/QtCore/qatomic_s390.h \
		/usr/include/qt5/QtCore/qatomic_sh4a.h \
		/usr/include/qt5/QtCore/qatomic_sparc.h \
		/usr/include/qt5/QtCore/qatomic_gcc.h \
		/usr/include/qt5/QtCore/qatomic_x86.h \
		/usr/include/qt5/QtCore/qatomic_cxx11.h \
		/usr/include/qt5/QtCore/qatomic_unix.h \
		/usr/include/qt5/QtCore/qmutex.h \
		/usr/include/qt5/QtCore/qlogging.h \
		/usr/include/qt5/QtCore/qflags.h \
		/usr/include/qt5/QtCore/qtypeinfo.h \
		/usr/include/qt5/QtCore/qtypetraits.h \
		/usr/include/qt5/QtCore/qsysinfo.h \
		/usr/include/qt5/QtCore/qobjectdefs.h \
		/usr/include/qt5/QtCore/qnamespace.h \
		/usr/include/qt5/QtCore/qobjectdefs_impl.h \
		/usr/include/qt5/QtGui/qwindowdefs_win.h \
		/usr/include/qt5/QtCore/qobject.h \
		/usr/include/qt5/QtCore/qstring.h \
		/usr/include/qt5/QtCore/qchar.h \
		/usr/include/qt5/QtCore/qbytearray.h \
		/usr/include/qt5/QtCore/qrefcount.h \
		/usr/include/qt5/QtCore/qarraydata.h \
		/usr/include/qt5/QtCore/qstringbuilder.h \
		/usr/include/qt5/QtCore/qlist.h \
		/usr/include/qt5/QtCore/qalgorithms.h \
		/usr/include/qt5/QtCore/qiterator.h \
		/usr/include/qt5/QtCore/qcoreevent.h \
		/usr/include/qt5/QtCore/qscopedpointer.h \
		/usr/include/qt5/QtCore/qmetatype.h \
		/usr/include/qt5/QtCore/qvarlengtharray.h \
		/usr/include/qt5/QtCore/qcontainerfwd.h \
		/usr/include/qt5/QtCore/qisenum.h \
		/usr/include/qt5/QtCore/qobject_impl.h \
		/usr/include/qt5/QtCore/qmargins.h \
		/usr/include/qt5/QtCore/qrect.h \
		/usr/include/qt5/QtCore/qsize.h \
		/usr/include/qt5/QtCore/qpoint.h \
		/usr/include/qt5/QtGui/qpaintdevice.h \
		/usr/include/qt5/QtGui/qpalette.h \
		/usr/include/qt5/QtGui/qcolor.h \
		/usr/include/qt5/QtGui/qrgb.h \
		/usr/include/qt5/QtCore/qstringlist.h \
		/usr/include/qt5/QtCore/qdatastream.h \
		/usr/include/qt5/QtCore/qiodevice.h \
		/usr/include/qt5/QtCore/qpair.h \
		/usr/include/qt5/QtCore/qregexp.h \
		/usr/include/qt5/QtCore/qstringmatcher.h \
		/usr/include/qt5/QtGui/qbrush.h \
		/usr/include/qt5/QtCore/qvector.h \
		/usr/include/qt5/QtGui/qmatrix.h \
		/usr/include/qt5/QtGui/qpolygon.h \
		/usr/include/qt5/QtGui/qregion.h \
		/usr/include/qt5/QtCore/qline.h \
		/usr/include/qt5/QtGui/qtransform.h \
		/usr/include/qt5/QtGui/qpainterpath.h \
		/usr/include/qt5/QtGui/qimage.h \
		/usr/include/qt5/QtGui/qpixmap.h \
		/usr/include/qt5/QtCore/qsharedpointer.h \
		/usr/include/qt5/QtCore/qshareddata.h \
		/usr/include/qt5/QtCore/qsharedpointer_impl.h \
		/usr/include/qt5/QtCore/qhash.h \
		/usr/include/qt5/QtGui/qfont.h \
		/usr/include/qt5/QtGui/qfontmetrics.h \
		/usr/include/qt5/QtGui/qfontinfo.h \
		/usr/include/qt5/QtWidgets/qsizepolicy.h \
		/usr/include/qt5/QtGui/qcursor.h \
		/usr/include/qt5/QtGui/qkeysequence.h \
		/usr/include/qt5/QtGui/qevent.h \
		/usr/include/qt5/QtCore/qvariant.h \
		/usr/include/qt5/QtCore/qmap.h \
		/usr/include/qt5/QtCore/qdebug.h \
		/usr/include/qt5/QtCore/qtextstream.h \
		/usr/include/qt5/QtCore/qlocale.h \
		/usr/include/qt5/QtCore/qset.h \
		/usr/include/qt5/QtCore/qcontiguouscache.h \
		/usr/include/qt5/QtCore/qurl.h \
		/usr/include/qt5/QtCore/qurlquery.h \
		/usr/include/qt5/QtCore/qfile.h \
		/usr/include/qt5/QtCore/qfiledevice.h \
		/usr/include/qt5/QtGui/qvector2d.h \
		/usr/include/qt5/QtGui/qtouchdevice.h \
		/usr/include/qt5/QtWidgets/qtabwidget.h \
		/usr/include/qt5/QtGui/qicon.h \
		/usr/include/qt5/QtWidgets/QLabel \
		/usr/include/qt5/QtWidgets/qlabel.h \
		/usr/include/qt5/QtWidgets/qframe.h \
		/usr/include/qt5/QtCore/QTimer \
		/usr/include/qt5/QtCore/qtimer.h \
		/usr/include/qt5/QtCore/qbasictimer.h \
		/usr/include/qt5/QtGui/QMouseEvent \
		Include/MainWindow.h
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) $(INCPATH) -I/usr/include/c++/4.8 -I/usr/include/x86_64-linux-gnu/c++/4.8 -I/usr/include/c++/4.8/backward -I/usr/lib/gcc/x86_64-linux-gnu/4.8/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/4.8/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include Include/MainWindow.h -o Bin/Linux/Release/.moc/moc_MainWindow.cpp

compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean 

####### Compile

Bin/Linux/Release/.obj/main.o: main.cpp Include/MainWindow.h \
		Include/Versioning.h \
		Include/Consciousness.h \
		/usr/include/qt5/QtWidgets/QMainWindow \
		/usr/include/qt5/QtWidgets/qmainwindow.h \
		/usr/include/qt5/QtWidgets/qwidget.h \
		/usr/include/qt5/QtGui/qwindowdefs.h \
		/usr/include/qt5/QtCore/qglobal.h \
		/usr/include/qt5/QtCore/qconfig.h \
		/usr/include/qt5/QtCore/qfeatures.h \
		/usr/include/qt5/QtCore/qsystemdetection.h \
		/usr/include/qt5/QtCore/qprocessordetection.h \
		/usr/include/qt5/QtCore/qcompilerdetection.h \
		/usr/include/qt5/QtCore/qglobalstatic.h \
		/usr/include/qt5/QtCore/qatomic.h \
		/usr/include/qt5/QtCore/qbasicatomic.h \
		/usr/include/qt5/QtCore/qatomic_bootstrap.h \
		/usr/include/qt5/QtCore/qgenericatomic.h \
		/usr/include/qt5/QtCore/qatomic_msvc.h \
		/usr/include/qt5/QtCore/qatomic_integrity.h \
		/usr/include/qt5/QtCore/qoldbasicatomic.h \
		/usr/include/qt5/QtCore/qatomic_vxworks.h \
		/usr/include/qt5/QtCore/qatomic_power.h \
		/usr/include/qt5/QtCore/qatomic_alpha.h \
		/usr/include/qt5/QtCore/qatomic_armv7.h \
		/usr/include/qt5/QtCore/qatomic_armv6.h \
		/usr/include/qt5/QtCore/qatomic_armv5.h \
		/usr/include/qt5/QtCore/qatomic_bfin.h \
		/usr/include/qt5/QtCore/qatomic_ia64.h \
		/usr/include/qt5/QtCore/qatomic_mips.h \
		/usr/include/qt5/QtCore/qatomic_s390.h \
		/usr/include/qt5/QtCore/qatomic_sh4a.h \
		/usr/include/qt5/QtCore/qatomic_sparc.h \
		/usr/include/qt5/QtCore/qatomic_gcc.h \
		/usr/include/qt5/QtCore/qatomic_x86.h \
		/usr/include/qt5/QtCore/qatomic_cxx11.h \
		/usr/include/qt5/QtCore/qatomic_unix.h \
		/usr/include/qt5/QtCore/qmutex.h \
		/usr/include/qt5/QtCore/qlogging.h \
		/usr/include/qt5/QtCore/qflags.h \
		/usr/include/qt5/QtCore/qtypeinfo.h \
		/usr/include/qt5/QtCore/qtypetraits.h \
		/usr/include/qt5/QtCore/qsysinfo.h \
		/usr/include/qt5/QtCore/qobjectdefs.h \
		/usr/include/qt5/QtCore/qnamespace.h \
		/usr/include/qt5/QtCore/qobjectdefs_impl.h \
		/usr/include/qt5/QtGui/qwindowdefs_win.h \
		/usr/include/qt5/QtCore/qobject.h \
		/usr/include/qt5/QtCore/qstring.h \
		/usr/include/qt5/QtCore/qchar.h \
		/usr/include/qt5/QtCore/qbytearray.h \
		/usr/include/qt5/QtCore/qrefcount.h \
		/usr/include/qt5/QtCore/qarraydata.h \
		/usr/include/qt5/QtCore/qstringbuilder.h \
		/usr/include/qt5/QtCore/qlist.h \
		/usr/include/qt5/QtCore/qalgorithms.h \
		/usr/include/qt5/QtCore/qiterator.h \
		/usr/include/qt5/QtCore/qcoreevent.h \
		/usr/include/qt5/QtCore/qscopedpointer.h \
		/usr/include/qt5/QtCore/qmetatype.h \
		/usr/include/qt5/QtCore/qvarlengtharray.h \
		/usr/include/qt5/QtCore/qcontainerfwd.h \
		/usr/include/qt5/QtCore/qisenum.h \
		/usr/include/qt5/QtCore/qobject_impl.h \
		/usr/include/qt5/QtCore/qmargins.h \
		/usr/include/qt5/QtCore/qrect.h \
		/usr/include/qt5/QtCore/qsize.h \
		/usr/include/qt5/QtCore/qpoint.h \
		/usr/include/qt5/QtGui/qpaintdevice.h \
		/usr/include/qt5/QtGui/qpalette.h \
		/usr/include/qt5/QtGui/qcolor.h \
		/usr/include/qt5/QtGui/qrgb.h \
		/usr/include/qt5/QtCore/qstringlist.h \
		/usr/include/qt5/QtCore/qdatastream.h \
		/usr/include/qt5/QtCore/qiodevice.h \
		/usr/include/qt5/QtCore/qpair.h \
		/usr/include/qt5/QtCore/qregexp.h \
		/usr/include/qt5/QtCore/qstringmatcher.h \
		/usr/include/qt5/QtGui/qbrush.h \
		/usr/include/qt5/QtCore/qvector.h \
		/usr/include/qt5/QtGui/qmatrix.h \
		/usr/include/qt5/QtGui/qpolygon.h \
		/usr/include/qt5/QtGui/qregion.h \
		/usr/include/qt5/QtCore/qline.h \
		/usr/include/qt5/QtGui/qtransform.h \
		/usr/include/qt5/QtGui/qpainterpath.h \
		/usr/include/qt5/QtGui/qimage.h \
		/usr/include/qt5/QtGui/qpixmap.h \
		/usr/include/qt5/QtCore/qsharedpointer.h \
		/usr/include/qt5/QtCore/qshareddata.h \
		/usr/include/qt5/QtCore/qsharedpointer_impl.h \
		/usr/include/qt5/QtCore/qhash.h \
		/usr/include/qt5/QtGui/qfont.h \
		/usr/include/qt5/QtGui/qfontmetrics.h \
		/usr/include/qt5/QtGui/qfontinfo.h \
		/usr/include/qt5/QtWidgets/qsizepolicy.h \
		/usr/include/qt5/QtGui/qcursor.h \
		/usr/include/qt5/QtGui/qkeysequence.h \
		/usr/include/qt5/QtGui/qevent.h \
		/usr/include/qt5/QtCore/qvariant.h \
		/usr/include/qt5/QtCore/qmap.h \
		/usr/include/qt5/QtCore/qdebug.h \
		/usr/include/qt5/QtCore/qtextstream.h \
		/usr/include/qt5/QtCore/qlocale.h \
		/usr/include/qt5/QtCore/qset.h \
		/usr/include/qt5/QtCore/qcontiguouscache.h \
		/usr/include/qt5/QtCore/qurl.h \
		/usr/include/qt5/QtCore/qurlquery.h \
		/usr/include/qt5/QtCore/qfile.h \
		/usr/include/qt5/QtCore/qfiledevice.h \
		/usr/include/qt5/QtGui/qvector2d.h \
		/usr/include/qt5/QtGui/qtouchdevice.h \
		/usr/include/qt5/QtWidgets/qtabwidget.h \
		/usr/include/qt5/QtGui/qicon.h \
		/usr/include/qt5/QtWidgets/QLabel \
		/usr/include/qt5/QtWidgets/qlabel.h \
		/usr/include/qt5/QtWidgets/qframe.h \
		/usr/include/qt5/QtCore/QTimer \
		/usr/include/qt5/QtCore/qtimer.h \
		/usr/include/qt5/QtCore/qbasictimer.h \
		/usr/include/qt5/QtGui/QMouseEvent \
		/usr/include/qt5/QtWidgets/QApplication \
		/usr/include/qt5/QtWidgets/qapplication.h \
		/usr/include/qt5/QtCore/qcoreapplication.h \
		/usr/include/qt5/QtCore/qeventloop.h \
		/usr/include/qt5/QtWidgets/qdesktopwidget.h \
		/usr/include/qt5/QtGui/qguiapplication.h \
		/usr/include/qt5/QtGui/qinputmethod.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Bin/Linux/Release/.obj/main.o main.cpp

Bin/Linux/Release/.obj/Consciousness.o: Source/Consciousness.cpp Include/Consciousness.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Bin/Linux/Release/.obj/Consciousness.o Source/Consciousness.cpp

Bin/Linux/Release/.obj/IntToStr.o: Source/IntToStr.cpp Include/IntToStr.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Bin/Linux/Release/.obj/IntToStr.o Source/IntToStr.cpp

Bin/Linux/Release/.obj/MainWindow.o: Source/MainWindow.cpp Include/MainWindow.h \
		Include/Versioning.h \
		Include/Consciousness.h \
		/usr/include/qt5/QtWidgets/QMainWindow \
		/usr/include/qt5/QtWidgets/qmainwindow.h \
		/usr/include/qt5/QtWidgets/qwidget.h \
		/usr/include/qt5/QtGui/qwindowdefs.h \
		/usr/include/qt5/QtCore/qglobal.h \
		/usr/include/qt5/QtCore/qconfig.h \
		/usr/include/qt5/QtCore/qfeatures.h \
		/usr/include/qt5/QtCore/qsystemdetection.h \
		/usr/include/qt5/QtCore/qprocessordetection.h \
		/usr/include/qt5/QtCore/qcompilerdetection.h \
		/usr/include/qt5/QtCore/qglobalstatic.h \
		/usr/include/qt5/QtCore/qatomic.h \
		/usr/include/qt5/QtCore/qbasicatomic.h \
		/usr/include/qt5/QtCore/qatomic_bootstrap.h \
		/usr/include/qt5/QtCore/qgenericatomic.h \
		/usr/include/qt5/QtCore/qatomic_msvc.h \
		/usr/include/qt5/QtCore/qatomic_integrity.h \
		/usr/include/qt5/QtCore/qoldbasicatomic.h \
		/usr/include/qt5/QtCore/qatomic_vxworks.h \
		/usr/include/qt5/QtCore/qatomic_power.h \
		/usr/include/qt5/QtCore/qatomic_alpha.h \
		/usr/include/qt5/QtCore/qatomic_armv7.h \
		/usr/include/qt5/QtCore/qatomic_armv6.h \
		/usr/include/qt5/QtCore/qatomic_armv5.h \
		/usr/include/qt5/QtCore/qatomic_bfin.h \
		/usr/include/qt5/QtCore/qatomic_ia64.h \
		/usr/include/qt5/QtCore/qatomic_mips.h \
		/usr/include/qt5/QtCore/qatomic_s390.h \
		/usr/include/qt5/QtCore/qatomic_sh4a.h \
		/usr/include/qt5/QtCore/qatomic_sparc.h \
		/usr/include/qt5/QtCore/qatomic_gcc.h \
		/usr/include/qt5/QtCore/qatomic_x86.h \
		/usr/include/qt5/QtCore/qatomic_cxx11.h \
		/usr/include/qt5/QtCore/qatomic_unix.h \
		/usr/include/qt5/QtCore/qmutex.h \
		/usr/include/qt5/QtCore/qlogging.h \
		/usr/include/qt5/QtCore/qflags.h \
		/usr/include/qt5/QtCore/qtypeinfo.h \
		/usr/include/qt5/QtCore/qtypetraits.h \
		/usr/include/qt5/QtCore/qsysinfo.h \
		/usr/include/qt5/QtCore/qobjectdefs.h \
		/usr/include/qt5/QtCore/qnamespace.h \
		/usr/include/qt5/QtCore/qobjectdefs_impl.h \
		/usr/include/qt5/QtGui/qwindowdefs_win.h \
		/usr/include/qt5/QtCore/qobject.h \
		/usr/include/qt5/QtCore/qstring.h \
		/usr/include/qt5/QtCore/qchar.h \
		/usr/include/qt5/QtCore/qbytearray.h \
		/usr/include/qt5/QtCore/qrefcount.h \
		/usr/include/qt5/QtCore/qarraydata.h \
		/usr/include/qt5/QtCore/qstringbuilder.h \
		/usr/include/qt5/QtCore/qlist.h \
		/usr/include/qt5/QtCore/qalgorithms.h \
		/usr/include/qt5/QtCore/qiterator.h \
		/usr/include/qt5/QtCore/qcoreevent.h \
		/usr/include/qt5/QtCore/qscopedpointer.h \
		/usr/include/qt5/QtCore/qmetatype.h \
		/usr/include/qt5/QtCore/qvarlengtharray.h \
		/usr/include/qt5/QtCore/qcontainerfwd.h \
		/usr/include/qt5/QtCore/qisenum.h \
		/usr/include/qt5/QtCore/qobject_impl.h \
		/usr/include/qt5/QtCore/qmargins.h \
		/usr/include/qt5/QtCore/qrect.h \
		/usr/include/qt5/QtCore/qsize.h \
		/usr/include/qt5/QtCore/qpoint.h \
		/usr/include/qt5/QtGui/qpaintdevice.h \
		/usr/include/qt5/QtGui/qpalette.h \
		/usr/include/qt5/QtGui/qcolor.h \
		/usr/include/qt5/QtGui/qrgb.h \
		/usr/include/qt5/QtCore/qstringlist.h \
		/usr/include/qt5/QtCore/qdatastream.h \
		/usr/include/qt5/QtCore/qiodevice.h \
		/usr/include/qt5/QtCore/qpair.h \
		/usr/include/qt5/QtCore/qregexp.h \
		/usr/include/qt5/QtCore/qstringmatcher.h \
		/usr/include/qt5/QtGui/qbrush.h \
		/usr/include/qt5/QtCore/qvector.h \
		/usr/include/qt5/QtGui/qmatrix.h \
		/usr/include/qt5/QtGui/qpolygon.h \
		/usr/include/qt5/QtGui/qregion.h \
		/usr/include/qt5/QtCore/qline.h \
		/usr/include/qt5/QtGui/qtransform.h \
		/usr/include/qt5/QtGui/qpainterpath.h \
		/usr/include/qt5/QtGui/qimage.h \
		/usr/include/qt5/QtGui/qpixmap.h \
		/usr/include/qt5/QtCore/qsharedpointer.h \
		/usr/include/qt5/QtCore/qshareddata.h \
		/usr/include/qt5/QtCore/qsharedpointer_impl.h \
		/usr/include/qt5/QtCore/qhash.h \
		/usr/include/qt5/QtGui/qfont.h \
		/usr/include/qt5/QtGui/qfontmetrics.h \
		/usr/include/qt5/QtGui/qfontinfo.h \
		/usr/include/qt5/QtWidgets/qsizepolicy.h \
		/usr/include/qt5/QtGui/qcursor.h \
		/usr/include/qt5/QtGui/qkeysequence.h \
		/usr/include/qt5/QtGui/qevent.h \
		/usr/include/qt5/QtCore/qvariant.h \
		/usr/include/qt5/QtCore/qmap.h \
		/usr/include/qt5/QtCore/qdebug.h \
		/usr/include/qt5/QtCore/qtextstream.h \
		/usr/include/qt5/QtCore/qlocale.h \
		/usr/include/qt5/QtCore/qset.h \
		/usr/include/qt5/QtCore/qcontiguouscache.h \
		/usr/include/qt5/QtCore/qurl.h \
		/usr/include/qt5/QtCore/qurlquery.h \
		/usr/include/qt5/QtCore/qfile.h \
		/usr/include/qt5/QtCore/qfiledevice.h \
		/usr/include/qt5/QtGui/qvector2d.h \
		/usr/include/qt5/QtGui/qtouchdevice.h \
		/usr/include/qt5/QtWidgets/qtabwidget.h \
		/usr/include/qt5/QtGui/qicon.h \
		/usr/include/qt5/QtWidgets/QLabel \
		/usr/include/qt5/QtWidgets/qlabel.h \
		/usr/include/qt5/QtWidgets/qframe.h \
		/usr/include/qt5/QtCore/QTimer \
		/usr/include/qt5/QtCore/qtimer.h \
		/usr/include/qt5/QtCore/qbasictimer.h \
		/usr/include/qt5/QtGui/QMouseEvent \
		Include/IntToStr.h \
		/usr/include/qt5/QtWidgets/QApplication \
		/usr/include/qt5/QtWidgets/qapplication.h \
		/usr/include/qt5/QtCore/qcoreapplication.h \
		/usr/include/qt5/QtCore/qeventloop.h \
		/usr/include/qt5/QtWidgets/qdesktopwidget.h \
		/usr/include/qt5/QtGui/qguiapplication.h \
		/usr/include/qt5/QtGui/qinputmethod.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Bin/Linux/Release/.obj/MainWindow.o Source/MainWindow.cpp

Bin/Linux/Release/.obj/Versioning.o: Source/Versioning.cpp Include/Versioning.h \
		Include/IntToStr.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Bin/Linux/Release/.obj/Versioning.o Source/Versioning.cpp

Bin/Linux/Release/.obj/moc_MainWindow.o: Bin/Linux/Release/.moc/moc_MainWindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Bin/Linux/Release/.obj/moc_MainWindow.o Bin/Linux/Release/.moc/moc_MainWindow.cpp

####### Install

install:   FORCE

uninstall:   FORCE

=======
>>>>>>> 8969ebdacb0db01774b5053feaf95768e380b1da
FORCE:

$(MAKEFILE).Debug: Makefile
$(MAKEFILE).Release: Makefile
